--
-- PostgreSQL database dump
--

\restrict GaERDaLYLIsX3TlRd2HOfnXNFaaGQSDWzx4CyaA83SYKoWbJ1ItgOpfWjLJrifh

-- Dumped from database version 18.3 (Ubuntu 18.3-1)
-- Dumped by pg_dump version 18.3 (Ubuntu 18.3-1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_sellerprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_sellerprofile (
    id bigint NOT NULL,
    store_name character varying(150),
    is_verified boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.accounts_sellerprofile OWNER TO postgres;

--
-- Name: accounts_sellerprofile_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_sellerprofile_categories (
    id bigint NOT NULL,
    sellerprofile_id bigint NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.accounts_sellerprofile_categories OWNER TO postgres;

--
-- Name: accounts_sellerprofile_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_sellerprofile_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_sellerprofile_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_sellerprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_sellerprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_sellerprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(10) NOT NULL,
    phone character varying(15) NOT NULL,
    city character varying(100) NOT NULL,
    state character varying(100) NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO postgres;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO postgres;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO postgres;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_cart; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.cart_cart OWNER TO postgres;

--
-- Name: cart_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_cartitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT cart_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.cart_cartitem OWNER TO postgres;

--
-- Name: cart_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_order (
    id bigint NOT NULL,
    order_id character varying(100) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    message text,
    created_at timestamp with time zone NOT NULL,
    buyer_id bigint NOT NULL,
    address text,
    city character varying(20),
    name character varying(20),
    phone character varying(10),
    state character varying(20)
);


ALTER TABLE public.orders_order OWNER TO postgres;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    total_price numeric(10,2) NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT orders_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.orders_orderitem OWNER TO postgres;

--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    image character varying(100)
);


ALTER TABLE public.products_category OWNER TO postgres;

--
-- Name: products_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_product (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    price numeric(10,2) NOT NULL,
    category_id bigint,
    seller_id bigint NOT NULL,
    subcategory_id bigint,
    created_at timestamp with time zone NOT NULL,
    description text,
    stock integer NOT NULL,
    product_type_id bigint,
    is_deleted boolean NOT NULL,
    CONSTRAINT products_product_stock_d3d0a648_check CHECK ((stock >= 0))
);


ALTER TABLE public.products_product OWNER TO postgres;

--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_productimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_productimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.products_productimage OWNER TO postgres;

--
-- Name: products_productimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_productimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_producttype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_producttype (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    image character varying(100),
    subcategory_id bigint NOT NULL
);


ALTER TABLE public.products_producttype OWNER TO postgres;

--
-- Name: products_producttype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_producttype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_producttype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_subcategory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_subcategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    image character varying(100),
    category_id bigint NOT NULL
);


ALTER TABLE public.products_subcategory OWNER TO postgres;

--
-- Name: products_subcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_subcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_subcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist_wishlist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wishlist_wishlist (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.wishlist_wishlist OWNER TO postgres;

--
-- Name: wishlist_wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wishlist_wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_sellerprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_sellerprofile (id, store_name, is_verified, created_at, user_id) FROM stdin;
5	WestSide	t	2026-05-05 10:35:13.458793+05:30	11
4	NewMe	t	2026-05-05 10:26:24.708393+05:30	10
2	H&M	t	2026-05-04 17:22:11.425857+05:30	8
10	Savana	f	2026-05-19 17:00:02.792772+05:30	20
\.


--
-- Data for Name: accounts_sellerprofile_categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_sellerprofile_categories (id, sellerprofile_id, category_id) FROM stdin;
2	2	2
3	2	3
5	4	2
6	5	1
7	5	2
13	10	2
14	10	3
\.


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, phone, city, state) FROM stdin;
20	pbkdf2_sha256$1200000$vcTZcFBScp6tewoCdhQsl2$L/BG6iJ93iL06v5M1K+GYhp5e8S7bdJlfayHIboVP2w=	2026-05-19 17:16:09.079714+05:30	f	Savana			savana@gmail.com	f	t	2026-05-19 17:00:02.192727+05:30	seller	4568529631	mumbai	maharashtra
15	pbkdf2_sha256$1200000$fW9LWIEGFYvayYBCA0VfrO$Lr1MTYdDuLvi8Zu7iYI6xT3cAXM92CeMTeMxAy6SSLA=	2026-05-12 17:15:39.380846+05:30	f	taylorSwift			ts@gmail.com	f	t	2026-05-12 16:30:13.760035+05:30	buyer	1596324789	surat	gujrat
11	pbkdf2_sha256$1200000$yruDVKyuSKTScSjEOcURWS$88pUIig1MUi7z2xG9G540xGMVmVxuwjm6LedJGaTvR8=	2026-05-19 17:33:54.154104+05:30	f	westside			wd@gmail.com	f	t	2026-05-05 10:35:12+05:30	seller	1596324789	pune	maharashtra
21	pbkdf2_sha256$1200000$uRA27MxPzgN49q8T31y372$ZruYvXy8zL85Kb/g/Yp+nlfCXjOKVd/TVoEHGgE7COg=	2026-05-19 17:35:51.844462+05:30	f	knn			knn@gmail.com	f	t	2026-05-19 17:13:48.223063+05:30	buyer	8905069970	surat	gujrat
7	pbkdf2_sha256$1200000$Wp4SwRHz9lwBPkkE509F1n$69rPUl75e+//8dx79AiLCqk4wexcWqtDF8YWGBYSEGc=	2026-05-04 16:20:20.685261+05:30	f	hey			hey@gmail.com	f	t	2026-05-04 16:14:35.814705+05:30	seller	1597894563	vadodara	gujrat
3	pbkdf2_sha256$1200000$2N2hSPYXmmbdL09Tudh37N$HJB77mY9Nmthgr2OEEKSrPsprzg1+0+QC0FWM117bpI=	2026-05-04 16:20:55.57412+05:30	f	knakrani			knakrani@gmail.com	f	t	2026-05-04 11:44:35.795037+05:30	buyer	1597534560	vadodara	gujrat
1	pbkdf2_sha256$1200000$BDCuNPJ5RZhyJX6BOmUrUX$6ATB1lEydY71yGOZtoiP25hedNkJtl1G72keB1ooTEs=	2026-05-19 15:43:39.981789+05:30	f	krusha			krusha@gmail.com	f	t	2026-05-04 11:20:10.180864+05:30	buyer	6355483492	surat	gujrat
10	pbkdf2_sha256$1200000$L9rcCS18rgMs9hMzewUjXc$QuUULbRnATIHD8zKZdGw4He/4nlEbxYuu5pjEy1TYl8=	2026-05-19 16:23:58.19978+05:30	f	newME			newme@gmail.com	f	t	2026-05-05 10:26:24+05:30	seller	9632587410	mumbai	maharashtra
23	pbkdf2_sha256$1200000$XbaguyiUvbVugfYtVKPr5y$XfkJ8+YZRezXZKicZwA1C3yBUjkfrHzs85BeMlqNyU0=	2026-05-20 10:29:53.973828+05:30	f	ruru			aadbc@gmail.com	f	t	2026-05-20 09:55:58.10459+05:30	buyer	1597534560	ahmedabad	gujrat
16	pbkdf2_sha256$1200000$nAqXh9wvgRgCYb8vwDFs25$k0Ojfnjo6l8swhgoxYAgSb8n9tshrIvMm1np667zp3A=	2026-05-20 10:30:14.345596+05:30	f	hk			hk@gmail.com	f	t	2026-05-12 16:40:16.60591+05:30	buyer	6355652835	mumbai	maharashtra
8	pbkdf2_sha256$1200000$Ih7eqbyTepwJG1I8AJ9Ngn$VTkQVq7xIb5dW5ulRE2qnyHunr0erJaUz/NU76IEWWM=	2026-05-20 10:31:44.606002+05:30	f	hm			hm@gmail.com	f	t	2026-05-04 17:22:10.843186+05:30	seller			
2	pbkdf2_sha256$1200000$zZE9SkvCCG0Mo7GMUsd1od$hpSVsUCC6I22aqmMaX+VrwGfAc8hTIAgyq9lcplYKvY=	2026-05-20 10:32:37.619158+05:30	t	admin			admin@gmail.com	t	t	2026-05-04 11:43:01.273666+05:30				
14	pbkdf2_sha256$1200000$wUO3eru1bCrayqeJ0FjFWr$vhtKGrY3yDrz26xPOOSoCXJao4ugao6EgOIFP5a2t0U=	2026-05-19 09:56:38.464154+05:30	f	xyz			abc@gmail.com	f	t	2026-05-08 17:11:52.465544+05:30	buyer	4598564641	pune	maharashtra
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
1	10	47
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add seller profile	7	add_sellerprofile
26	Can change seller profile	7	change_sellerprofile
27	Can delete seller profile	7	delete_sellerprofile
28	Can view seller profile	7	view_sellerprofile
29	Can add category	8	add_category
30	Can change category	8	change_category
31	Can delete category	8	delete_category
32	Can view category	8	view_category
33	Can add sub category	10	add_subcategory
34	Can change sub category	10	change_subcategory
35	Can delete sub category	10	delete_subcategory
36	Can view sub category	10	view_subcategory
37	Can add product	9	add_product
38	Can change product	9	change_product
39	Can delete product	9	delete_product
40	Can view product	9	view_product
41	Can add product image	11	add_productimage
42	Can change product image	11	change_productimage
43	Can delete product image	11	delete_productimage
44	Can view product image	11	view_productimage
45	Can add product type	12	add_producttype
46	Can change product type	12	change_producttype
47	Can delete product type	12	delete_producttype
48	Can view product type	12	view_producttype
49	Can add wishlist	13	add_wishlist
50	Can change wishlist	13	change_wishlist
51	Can delete wishlist	13	delete_wishlist
52	Can view wishlist	13	view_wishlist
53	Can add cart	14	add_cart
54	Can change cart	14	change_cart
55	Can delete cart	14	delete_cart
56	Can view cart	14	view_cart
57	Can add cart item	15	add_cartitem
58	Can change cart item	15	change_cartitem
59	Can delete cart item	15	delete_cartitem
60	Can view cart item	15	view_cartitem
61	Can add wishlist	16	add_wishlist
62	Can change wishlist	16	change_wishlist
63	Can delete wishlist	16	delete_wishlist
64	Can view wishlist	16	view_wishlist
65	Can add order	17	add_order
66	Can change order	17	change_order
67	Can delete order	17	delete_order
68	Can view order	17	view_order
69	Can add order item	18	add_orderitem
70	Can change order item	18	change_orderitem
71	Can delete order item	18	delete_orderitem
72	Can view order item	18	view_orderitem
\.


--
-- Data for Name: cart_cart; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cart_cart (id, created_at, user_id) FROM stdin;
1	2026-05-11 11:08:46.539548+05:30	14
3	2026-05-12 16:33:27.581225+05:30	15
4	2026-05-12 16:40:30.246357+05:30	16
2	2026-05-11 18:27:18.052934+05:30	1
5	2026-05-19 17:14:17.711634+05:30	21
\.


--
-- Data for Name: cart_cartitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cart_cartitem (id, quantity, cart_id, product_id) FROM stdin;
63	1	4	22
64	5	1	49
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-05-04 12:17:33.186481+05:30	4	abc	3		6	2
2	2026-05-04 12:20:51.327316+05:30	5	abc	3		6	2
3	2026-05-04 15:32:43.875572+05:30	1	Footwear	1	[{"added": {}}]	8	2
4	2026-05-04 15:32:48.11286+05:30	2	Clothes	1	[{"added": {}}]	8	2
5	2026-05-04 15:33:10.006094+05:30	3	Accessories	1	[{"added": {}}]	8	2
6	2026-05-04 16:52:17.643312+05:30	1	hey	2	[{"changed": {"fields": ["Store name"]}}]	7	2
7	2026-05-04 16:52:21.755523+05:30	1	hey	2	[{"changed": {"fields": ["Is verified"]}}]	7	2
8	2026-05-04 17:22:48.861403+05:30	2	hm	2	[{"changed": {"fields": ["Is verified"]}}]	7	2
9	2026-05-05 09:58:45.44358+05:30	5	Clothes	3		8	2
10	2026-05-05 09:58:45.443657+05:30	4	Clothes	3		8	2
11	2026-05-05 10:01:08.593453+05:30	3	newME	2	[{"changed": {"fields": ["Is verified"]}}]	7	2
12	2026-05-05 10:25:42.828329+05:30	3	newME	3		7	2
13	2026-05-05 10:25:50.355171+05:30	9	newME	3		6	2
14	2026-05-05 10:27:07.397768+05:30	4	newME	2	[{"changed": {"fields": ["Is verified"]}}]	7	2
15	2026-05-05 10:27:18.400549+05:30	2	Clothes	2	[{"changed": {"fields": ["Image"]}}]	8	2
16	2026-05-05 10:31:48.869582+05:30	1	Footwear	2	[{"changed": {"fields": ["Image"]}}]	8	2
17	2026-05-05 10:32:37.699359+05:30	3	Accessories	2	[{"changed": {"fields": ["Image"]}}]	8	2
18	2026-05-05 10:35:53.56083+05:30	5	westside	2	[{"changed": {"fields": ["Store name"]}}]	7	2
19	2026-05-05 10:36:00.558783+05:30	5	westside	2	[]	7	2
20	2026-05-05 10:36:07.070258+05:30	11	westside	2	[]	6	2
21	2026-05-05 14:26:25.657351+05:30	1	Men	1	[{"added": {}}]	10	2
22	2026-05-05 14:26:37.246651+05:30	1	Men	2	[]	10	2
23	2026-05-05 14:26:57.540804+05:30	2	women	1	[{"added": {}}]	10	2
24	2026-05-05 14:27:14.285704+05:30	3	kids	1	[{"added": {}}]	10	2
25	2026-05-05 14:27:26.341577+05:30	4	men	1	[{"added": {}}]	10	2
26	2026-05-05 14:27:37.251155+05:30	5	women	1	[{"added": {}}]	10	2
27	2026-05-05 14:27:50.775141+05:30	6	kids	1	[{"added": {}}]	10	2
28	2026-05-05 16:12:21.008879+05:30	7	watches	1	[{"added": {}}]	10	2
29	2026-05-05 16:12:35.961297+05:30	8	jewellery	1	[{"added": {}}]	10	2
30	2026-05-05 16:12:54.30359+05:30	9	bags	1	[{"added": {}}]	10	2
31	2026-05-05 16:26:46.511124+05:30	1	shirt	1	[{"added": {}}]	12	2
32	2026-05-05 16:27:00.482598+05:30	2	jeans	1	[{"added": {}}]	12	2
33	2026-05-05 16:27:24.054309+05:30	3	Top	1	[{"added": {}}]	12	2
34	2026-05-05 16:27:34.241161+05:30	4	Dress	1	[{"added": {}}]	12	2
35	2026-05-05 16:27:47.438414+05:30	5	Jeans	1	[{"added": {}}]	12	2
36	2026-05-05 16:31:03.21208+05:30	6	Dress	1	[{"added": {}}]	12	2
37	2026-05-05 16:31:15.225557+05:30	7	Shorts	1	[{"added": {}}]	12	2
38	2026-05-05 16:31:25.964355+05:30	8	Tshirt	1	[{"added": {}}]	12	2
39	2026-05-05 16:31:37.284001+05:30	9	Tshirt	1	[{"added": {}}]	12	2
40	2026-05-06 10:03:14.194095+05:30	3	kids	2	[{"changed": {"fields": ["Image"]}}]	10	2
41	2026-05-06 10:03:27.95072+05:30	2	women	2	[{"changed": {"fields": ["Image"]}}]	10	2
42	2026-05-06 10:03:38.399731+05:30	1	Men	2	[{"changed": {"fields": ["Image"]}}]	10	2
43	2026-05-06 10:15:59.493685+05:30	2	ProductImage object (2)	2	[{"changed": {"fields": ["Image"]}}]	11	2
44	2026-05-06 10:19:36.655339+05:30	3	ProductImage object (3)	2	[{"changed": {"fields": ["Image"]}}]	11	2
45	2026-05-06 11:18:34.895909+05:30	7	Cute_dress	3		9	2
46	2026-05-06 11:20:05.059856+05:30	8	Dress	3		9	2
47	2026-05-06 11:20:46.977552+05:30	5	westside	2	[{"changed": {"fields": ["Is verified"]}}]	7	2
48	2026-05-06 11:30:20.627026+05:30	10	ProductImage object (10)	2	[]	11	2
49	2026-05-06 15:43:45.79894+05:30	6	kids	2	[{"changed": {"fields": ["Image"]}}]	10	2
50	2026-05-06 15:43:55.517052+05:30	5	women	2	[{"changed": {"fields": ["Image"]}}]	10	2
51	2026-05-06 15:44:03.933376+05:30	4	men	2	[{"changed": {"fields": ["Image"]}}]	10	2
52	2026-05-06 15:45:10.174639+05:30	9	bags	2	[{"changed": {"fields": ["Image"]}}]	10	2
53	2026-05-06 15:45:17.956233+05:30	8	jewellery	2	[{"changed": {"fields": ["Image"]}}]	10	2
54	2026-05-06 15:45:33.120292+05:30	7	watches	2	[{"changed": {"fields": ["Image"]}}]	10	2
55	2026-05-06 17:31:24.936529+05:30	7	watches	2	[{"changed": {"fields": ["Image"]}}]	10	2
56	2026-05-06 17:33:59.641484+05:30	1	Footwear	2	[{"changed": {"fields": ["Image"]}}]	8	2
57	2026-05-06 17:35:29.750374+05:30	3	Accessories	2	[{"changed": {"fields": ["Image"]}}]	8	2
58	2026-05-06 17:38:16.034487+05:30	8	jewellery	2	[{"changed": {"fields": ["Image"]}}]	10	2
59	2026-05-06 17:46:37.324091+05:30	3	kids_clothes	2	[{"changed": {"fields": ["Name"]}}]	10	2
60	2026-05-06 17:46:46.711658+05:30	2	women_clothes	2	[{"changed": {"fields": ["Name"]}}]	10	2
61	2026-05-06 17:46:56.126233+05:30	1	Men_clothes	2	[{"changed": {"fields": ["Name"]}}]	10	2
62	2026-05-06 17:53:20.880393+05:30	10	shoes	1	[{"added": {}}]	12	2
63	2026-05-06 17:53:37.887749+05:30	11	shoes	1	[{"added": {}}]	12	2
64	2026-05-06 17:54:00.193349+05:30	12	shoes	1	[{"added": {}}]	12	2
65	2026-05-06 18:01:39.227839+05:30	13	Sliders	1	[{"added": {}}]	12	2
66	2026-05-06 18:01:59.217593+05:30	14	Sliders	1	[{"added": {}}]	12	2
67	2026-05-06 18:02:21.44609+05:30	15	Sliders	1	[{"added": {}}]	12	2
68	2026-05-06 18:06:02.162172+05:30	16	Clogs	1	[{"added": {}}]	12	2
69	2026-05-06 18:19:39.560944+05:30	17	Rings	1	[{"added": {}}]	12	2
70	2026-05-06 18:19:55.643517+05:30	18	Bracelets	1	[{"added": {}}]	12	2
71	2026-05-06 18:20:14.474982+05:30	19	Necklace	1	[{"added": {}}]	12	2
72	2026-05-07 10:06:51.115437+05:30	5	women	2	[{"changed": {"fields": ["Image"]}}]	10	2
73	2026-05-07 10:10:25.22627+05:30	5	westside	2	[]	7	2
74	2026-05-07 11:46:54.349472+05:30	20	Wo	1	[{"added": {}}]	12	2
75	2026-05-07 11:47:18.4451+05:30	20	Women_Bags	2	[{"changed": {"fields": ["Name", "Image"]}}]	12	2
76	2026-05-07 11:47:41.44034+05:30	21	Men_Bags	1	[{"added": {}}]	12	2
77	2026-05-07 11:48:14.18146+05:30	22	Women_Watches	1	[{"added": {}}]	12	2
78	2026-05-07 11:48:40.572482+05:30	23	Men_Watches	1	[{"added": {}}]	12	2
79	2026-05-07 12:33:12.851776+05:30	1	Footwear	2	[{"changed": {"fields": ["Image"]}}]	8	2
80	2026-05-07 12:40:51.811828+05:30	1	Footwear	2	[{"changed": {"fields": ["Image"]}}]	8	2
81	2026-05-07 14:49:40.862275+05:30	1	Footwear	2	[{"changed": {"fields": ["Image"]}}]	8	2
82	2026-05-08 12:57:13.781757+05:30	1	krusha - Tshirt	2	[]	13	2
83	2026-05-11 15:48:37.272163+05:30	8	CartItem object (8)	2	[]	15	2
84	2026-05-11 15:48:42.607063+05:30	3	CartItem object (3)	2	[]	15	2
85	2026-05-11 15:57:49.146025+05:30	10	newME	2	[{"changed": {"fields": ["User permissions"]}}]	6	2
86	2026-05-11 16:01:53.826542+05:30	8	CartItem object (8)	2	[]	15	2
87	2026-05-12 11:59:56.72852+05:30	2	krusha	2	[]	14	2
88	2026-05-12 12:01:00.803266+05:30	15	Trendy_Bag	2	[]	15	2
89	2026-05-12 12:01:26.08355+05:30	4	ORD8489	2	[]	17	2
90	2026-05-12 12:01:32.650508+05:30	2	ORD9706	2	[]	17	2
91	2026-05-12 12:29:56.798774+05:30	6	ORD2663	2	[]	17	2
92	2026-05-12 12:30:16.003197+05:30	2	Trendy_Bag	2	[]	18	2
93	2026-05-12 15:06:09.294493+05:30	2	Trendy_Bag	2	[]	18	2
94	2026-05-12 15:06:12.94638+05:30	3	Trendy_Bag	2	[]	18	2
95	2026-05-12 15:06:15.623808+05:30	4	shoes	2	[]	18	2
96	2026-05-12 15:06:19.136314+05:30	5	shoes	2	[]	18	2
97	2026-05-12 15:06:26.432173+05:30	2	Trendy_Bag	2	[]	18	2
98	2026-05-12 17:18:36.778573+05:30	13	Golden_bracelet	2	[]	18	2
99	2026-05-12 17:19:00.042804+05:30	14	ORD1760	2	[]	17	2
100	2026-05-15 17:05:40.228358+05:30	2	krusha	2	[]	14	2
101	2026-05-15 17:42:31.753047+05:30	6	admin	2	[]	7	2
102	2026-05-18 17:08:21.5179+05:30	6	admin	3		7	2
103	2026-05-19 16:24:28.08902+05:30	4	newME	2	[]	7	2
104	2026-05-19 16:24:48.579674+05:30	2	hm	2	[]	7	2
105	2026-05-19 16:59:01.294169+05:30	18	sad	3		6	2
106	2026-05-19 16:59:09.419801+05:30	17	asd	3		6	2
107	2026-05-20 09:54:59.322722+05:30	22	asa	3		6	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	accounts	sellerprofile
8	products	category
9	products	product
10	products	subcategory
11	products	productimage
12	products	producttype
13	products	wishlist
14	cart	cart
15	cart	cartitem
16	wishlist	wishlist
17	orders	order
18	orders	orderitem
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-04 10:51:09.279331+05:30
2	contenttypes	0002_remove_content_type_name	2026-05-04 10:57:18.662123+05:30
3	auth	0001_initial	2026-05-04 10:57:18.687008+05:30
4	auth	0002_alter_permission_name_max_length	2026-05-04 10:57:18.694088+05:30
5	auth	0003_alter_user_email_max_length	2026-05-04 10:57:18.705627+05:30
6	auth	0004_alter_user_username_opts	2026-05-04 10:57:18.71209+05:30
7	auth	0005_alter_user_last_login_null	2026-05-04 10:57:18.717143+05:30
8	auth	0006_require_contenttypes_0002	2026-05-04 10:57:18.719659+05:30
9	auth	0007_alter_validators_add_error_messages	2026-05-04 10:57:18.724161+05:30
10	auth	0008_alter_user_username_max_length	2026-05-04 10:57:18.729385+05:30
11	auth	0009_alter_user_last_name_max_length	2026-05-04 10:57:18.734729+05:30
12	auth	0010_alter_group_name_max_length	2026-05-04 10:57:18.744253+05:30
13	auth	0011_update_proxy_permissions	2026-05-04 10:57:18.750829+05:30
14	auth	0012_alter_user_first_name_max_length	2026-05-04 10:57:18.756133+05:30
15	accounts	0001_initial	2026-05-04 10:57:18.780691+05:30
16	admin	0001_initial	2026-05-04 10:57:18.80656+05:30
17	admin	0002_logentry_remove_auto_add	2026-05-04 10:57:18.813241+05:30
18	admin	0003_logentry_add_action_flag_choices	2026-05-04 10:57:18.819277+05:30
19	sessions	0001_initial	2026-05-04 10:57:18.827518+05:30
20	products	0001_initial	2026-05-04 15:05:46.732394+05:30
21	accounts	0002_sellerprofile	2026-05-04 15:05:46.752661+05:30
22	products	0002_remove_category_image	2026-05-04 15:31:54.048802+05:30
23	products	0003_category_image_alter_category_name_subcategory_and_more	2026-05-04 18:17:17.139383+05:30
24	products	0004_remove_product_image_product_created_at_and_more	2026-05-05 12:24:45.334376+05:30
25	products	0005_alter_product_stock	2026-05-06 11:55:25.507174+05:30
26	products	0006_wishlist	2026-05-08 12:13:59.866865+05:30
27	products	0007_delete_wishlist	2026-05-08 15:03:19.693034+05:30
28	cart	0001_initial	2026-05-08 15:03:19.736444+05:30
29	wishlist	0001_initial	2026-05-08 15:03:19.759474+05:30
30	orders	0001_initial	2026-05-11 15:11:41.051826+05:30
31	orders	0002_order_address_order_city_order_name_order_phone_and_more	2026-05-12 10:42:22.792295+05:30
32	orders	0003_alter_order_city_alter_order_state	2026-05-12 10:48:44.527069+05:30
33	orders	0004_orderitem	2026-05-12 12:26:16.726225+05:30
34	orders	0005_orderitem_status	2026-05-13 12:24:08.21842+05:30
35	products	0008_product_is_deleted	2026-05-14 15:02:30.17272+05:30
36	orders	0006_alter_orderitem_product	2026-05-19 09:46:40.146896+05:30
37	orders	0007_alter_order_buyer	2026-05-19 11:46:38.257674+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
2fucm95t22b6egeo0e0r6yzig9sasptt	.eJxVjEEOwiAQRe_C2hDBGRhcuu8ZGhhGqRpISrsy3l2bdKHb_977LzXGdSnj2mUep6zOyqrD75YiP6RuIN9jvTXNrS7zlPSm6J12PbQsz8vu_h2U2Mu3NsdMyZsMGdggYxChhI6Bg0VjOXh_IrAUr9YDJyFCFxAJ0DlDLOr9AdG7Nwg:1wPZ4n:_KqbsnNQak9yqfM_FgsAaidUHVBlxhrIXUtbK2-Gv3M	2026-06-03 10:32:37.621929+05:30
\.


--
-- Data for Name: orders_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_order (id, order_id, total_amount, message, created_at, buyer_id, address, city, name, phone, state) FROM stdin;
1	ORD6890	15200.00	your order has been placed successfully!	2026-05-12 10:44:16.068189+05:30	1	afcea	surat	fsdaf	1596324789	gujrat
3	ORD4016	5849.00	your order has been placed successfully!	2026-05-12 11:34:14.427043+05:30	1	dasdwqwww	surat	dadwew	1231216355	gujrat
4	ORD8489	14600.00	your order has been placed successfully!	2026-05-12 11:57:05.411394+05:30	14	dawdwq	mumbai	daqwd	1596324789	maharashtra
2	ORD9706	4400.00	your order has been placed successfully!	2026-05-12 10:49:13.1207+05:30	1	2dsfvVG	pune	aswdcawf	635242354	maharashtra
5	ORD4390	6600.00	your order has been placed successfully!	2026-05-12 12:27:34.213589+05:30	1	A-503 hill view,mumbai.	mumbai	krusha	1597534560	maharashtra
6	ORD2663	6600.00	your order has been placed successfully!	2026-05-12 12:29:25.93524+05:30	1	A-503 hill view,mumbai.	mumbai	krusha	1597534560	maharashtra
7	ORD3382	19800.00	your order has been placed successfully!	2026-05-12 14:44:06.474309+05:30	14	dqwdxq	mumbai	wqewde	1596324789	maharashtra
8	ORD4927	12000.00	your order has been placed successfully!	2026-05-12 14:45:51.938835+05:30	1	250,iwdoiehoi	vadodara	eqdqd	9632587415	gujrat
9	ORD5240	15000.00	your order has been placed successfully!	2026-05-12 14:55:34.065001+05:30	14	efrf	vadodara	gfdsa	1597894563	gujrat
10	ORD4472	7250.00	your order has been placed successfully!	2026-05-12 16:41:50.128285+05:30	16	1401,ihdfhqh	mumbai	hk	6355483492	maharashtra
11	ORD3012	5000.00	your order has been placed successfully!	2026-05-12 17:09:46.247012+05:30	16	hktyujed5yh	mumbai	hk	6355483492	maharashtra
12	ORD1001	1409.00	your order has been placed successfully!	2026-05-12 17:10:51.347718+05:30	16	etfgvqrewg	pune	feg	4697446432	maharashtra
13	ORD5217	5450.00	your order has been placed successfully!	2026-05-12 17:13:32.973786+05:30	16	fwfcgw	mumbai	asdcaf	1596324789	maharashtra
14	ORD1760	8299.00	your order has been placed successfully!	2026-05-12 17:16:41.533999+05:30	15	feknkl	london	ts	1597233563	uk
15	ORD1072	5900.00	your order has been placed successfully!	2026-05-12 18:03:01.206954+05:30	16	ewfbhwa	vadodara	fvgg	5423653876	gujrat
16	ORD5378	5900.00	your order has been placed successfully!	2026-05-12 18:04:00.036704+05:30	16	jntdrj	mumbai	jndtrjn	9632587410	maharashtra
17	ORD8330	8500.00	your order has been placed successfully!	2026-05-12 18:10:16.23949+05:30	16	asfcv AQ	rajkot	Jena	1597324424	gujrat
18	ORD4918	18650.00	your order has been placed successfully!	2026-05-14 11:33:20.191067+05:30	16	B-1404,yamuna palace.	surat	hk	6355652835	gujrat
19	ORD8582	27595.00	your order has been placed successfully!	2026-05-14 11:37:50.657796+05:30	16	1021,sfgbrhb	ahmedabad	hkn	1596324789	gujrat
20	ORD4535	1199.00	your order has been placed successfully!	2026-05-14 16:26:11.679958+05:30	14	324sdf	pune	xyz	1597252613	maharashtra
21	ORD6010	7349.00	your order has been placed successfully!	2026-05-15 11:55:34.024548+05:30	1	frewf	surat	asdf	9632587410	gujrat
22	ORD4130	11000.00	your order has been placed successfully!	2026-05-19 17:15:46.395792+05:30	21	c-302idrqoi	surat	krusha	8905069970	gujrat
\.


--
-- Data for Name: orders_orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_orderitem (id, quantity, price, total_price, order_id, product_id, seller_id, status) FROM stdin;
9	1	5000.00	5000.00	11	13	8	Pending
10	1	959.00	959.00	12	17	11	Pending
16	1	5000.00	5000.00	16	10	11	Pending
17	1	2600.00	2600.00	17	20	10	Pending
14	2	1650.00	3300.00	14	22	10	Packed
11	1	450.00	450.00	12	12	11	Packed
5	5	3000.00	15000.00	9	16	11	Delivered
15	1	5000.00	5000.00	15	10	11	Pending
8	1	450.00	450.00	10	12	11	Cancelled
20	1	2600.00	2600.00	19	20	10	Pending
21	1	899.00	899.00	20	36	11	Pending
22	3	100.00	300.00	20	46	8	Pending
2	1	6600.00	6600.00	6	23	8	Delivered
6	1	5000.00	5000.00	10	13	8	Shipped
7	1	1800.00	1800.00	10	2	8	Packed
12	1	1800.00	1800.00	13	2	8	Cancelled
23	1	2699.00	2699.00	21	37	11	Pending
24	1	4650.00	4650.00	21	45	8	Pending
19	5	4999.00	24995.00	19	14	8	Delivered
3	3	6600.00	19800.00	7	23	8	Delivered
18	1	6600.00	6600.00	18	23	8	Delivered
13	1	4999.00	4999.00	14	14	8	Delivered
4	4	3000.00	12000.00	8	16	11	Delivered
26	1	6000.00	6000.00	22	53	20	Pending
25	1	5000.00	5000.00	22	10	11	Packed
\.


--
-- Data for Name: products_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_category (id, name, image) FROM stdin;
2	Clothes	categories/clothes_I10Y7MP.jpeg
3	Accessories	categories/accessories.jpg
1	Footwear	categories/footwear_accessories_Gv7nbP5.jpg
\.


--
-- Data for Name: products_product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_product (id, name, price, category_id, seller_id, subcategory_id, created_at, description, stock, product_type_id, is_deleted) FROM stdin;
21	kids_dress	3100.00	2	10	3	2026-05-07 10:19:44.654196+05:30	Beautiful kids dress made with soft and comfortable fabric, perfect for daily wear and special occasions. Designed with a stylish look and lightweight material to keep kids comfortable all day long.	20	6	f
16	shoes	4000.00	1	11	5	2026-05-07 10:12:42.368555+05:30	Lightweight Breathable Mesh Running Shoes. Features shock-absorbing soles and arch support. Durable enough for high-impact training."	8	10	f
37	Clogs	2699.00	1	11	4	2026-05-12 17:40:44.254321+05:30	Stylish and lightweight men’s clogs designed for all-day comfort and everyday use. Made with durable, breathable material and a cushioned sole for a soft walking experience. Easy slip-on design with excellent grip, perfect for casual outings, travel, beach wear, and daily indoor or outdoor use.	8	16	f
34	Pearl_Necklace	2200.00	3	8	8	2026-05-08 15:41:29.989418+05:30	Beautiful pearl necklace designed with elegant finishing and timeless style. Made with high-quality pearls that add a graceful and luxurious touch to any outfit. Perfect for weddings, parties, festive occasions, or daily fashion wear. Lightweight, comfortable, and ideal for a classy modern look.	7	19	f
17	Sliders	959.00	1	11	6	2026-05-07 10:13:37.187691+05:30	Comfortable and lightweight kids sliders designed for daily wear. Made with soft and durable material, providing a perfect fit, easy grip, and all-day comfort for indoor and outdoor use.	19	15	f
5	Brown_Top	2000.00	2	8	2	2026-05-06 10:32:27.014267+05:30	Trendy and fashionable women's top crafted for modern style. Lightweight, comfortable, and easy to pair with jeans, skirts, or trousers for a chic look.	5	3	f
3	Shirt	1000.00	2	8	1	2026-05-06 10:18:33.454374+05:30	This men's shirt is crafted from breathable cotton material, offering all-day comfort and durability. Designed with a modern fit, it is ideal for office wear, meetings, and formal events.	10	1	f
33	Titan_Watch	6800.00	3	8	7	2026-05-08 15:39:38.628675+05:30	Elegant women’s watch with a stylish and modern design, perfect for daily wear and special occasions. Crafted with a premium finish, comfortable strap, and durable dial for a classy and timeless look. Lightweight, fashionable, and easy to pair with both casual and party outfits.	6	22	f
23	Trendy_Bag	6600.00	3	8	9	2026-05-07 11:50:21.600071+05:30	Stylish women's bag designed with premium-quality material and a modern look. Spacious, lightweight, and comfortable to carry, making it perfect for daily use, shopping, office, and casual outings.	5	20	f
12	kids_dresss	450.00	2	11	3	2026-05-06 15:42:06.310902+05:30	"Lightweight Linen Party Shirt. Stylish yet comfortable for long hours. Includes soft-touch inner lining."	8	6	f
2	cotten_shirt	1800.00	2	8	1	2026-05-06 10:14:45.195303+05:30	Upgrade your wardrobe with this stylish men's shirt. Made from soft and durable fabric, it provides a perfect blend of comfort and fashion. Suitable for casual outings, office wear, and special occasions.	18	1	f
20	Jeans_women	2600.00	2	10	2	2026-05-07 10:17:39.443918+05:30	Stylish women's jeans made with premium-quality denim fabric for comfort and durability. Designed with a modern fit and trendy look, perfect for casual outings, daily wear, and all-day comfort.	15	5	f
22	Tshirt	1650.00	2	10	1	2026-05-07 10:24:10.772856+05:30	Comfortable and stylish men's t-shirt made with soft and breathable fabric for all-day comfort. Designed with a modern fit and trendy look, perfect for casual wear, outings, and everyday use.	10	9	f
9	dressss	452.00	2	11	3	2026-05-06 11:32:21.110717+05:30	This kids dress is designed with soft, skin-friendly fabric to ensure maximum comfort. Its stylish pattern and lightweight feel make it ideal for both casual and festive occasions. Easy to wear and perfect for active kids.	6	6	f
40	Watch	6400.00	3	8	7	2026-05-14 12:32:09.18988+05:30	Elegant and stylish women’s watch designed to add a perfect touch to both casual and formal outfits. Crafted with a comfortable strap, durable build, and premium finish for everyday wear. Features a modern dial design with precise time movement, making it a perfect choice for fashion and functionality.	7	22	f
35	Denim_shorts	1100.00	2	11	3	2026-05-12 17:37:25.327291+05:30	Soft and comfortable denim shorts for kids, perfect for everyday wear. Made with breathable fabric and a flexible fit for easy movement during playtime. Features a stylish casual design, durable stitching, and convenient pockets for added comfort and functionality. Perfect for outings, school, and summer adventures.	14	7	f
14	Golden_bracelet	4999.00	3	8	8	2026-05-07 10:04:27.313722+05:30	Elegant gold bracelet crafted with premium-quality material and a stylish finish. Perfect for daily wear, parties, and special occasions.	4	18	f
42	Bag	5550.00	3	8	9	2026-05-14 15:03:35.379494+05:30	Stylish and durable men’s bag designed for everyday use, office, travel, and casual outings. Made with high-quality material and a modern design, it offers spacious compartments to carry essentials like wallet, laptop, books, and accessories comfortably. Features strong zippers, adjustable straps, and a premium finish for both comfort and style.	11	21	t
36	Tshirt	899.00	2	11	3	2026-05-12 17:39:10.055596+05:30	Comfortable and stylish kids T-shirt made with soft, breathable cotton fabric for all-day comfort. Designed with a trendy casual look, perfect for daily wear, playtime, outings, and school activities. Lightweight, skin-friendly, and easy to wash, making it ideal for active kids.	10	8	f
13	Diamond_Ring	8000.00	3	8	8	2026-05-07 09:59:46.935098+05:30	Beautiful diamond ring designed with a timeless and luxurious look. Its brilliant shine and elegant craftsmanship make it ideal for parties, weddings, and everyday elegance.	4	17	f
10	Dress	5000.00	2	11	2	2026-05-06 14:47:40.258752+05:30	Stylish women's dress designed with modern fashion trends. Lightweight, comfortable, and perfect for parties, outings, and everyday wear.	7	4	f
43	Bag	5450.00	3	8	9	2026-05-14 15:06:49.141624+05:30	Stylish and durable men’s bag designed for everyday use, office, travel, and casual outings. Made with high-quality material and a modern design, it offers spacious compartments to carry essentials like wallet, laptop, books, and accessories comfortably. Features strong zippers, adjustable straps, and a premium finish for both comfort and style.	11	21	t
44	Bag	4650.00	3	8	9	2026-05-14 15:29:39.184747+05:30	Stylish and durable men’s bag designed for everyday use, office, travel, and casual outings. Made with high-quality material and a modern design, it offers spacious compartments to carry essentials like wallet, laptop, books, and accessories comfortably. Features strong zippers, adjustable straps, and a premium finish for both comfort and style.	11	21	t
46	Necklace	100.00	3	8	8	2026-05-14 16:25:08.793467+05:30	afevfc	2	19	t
47	Tshirt	1400.00	2	8	1	2026-05-15 09:36:40.245876+05:30	Comfortable and stylish men’s T-shirt designed for everyday casual wear. Made with soft and breathable fabric for all-day comfort, it features a modern fit and trendy design that pairs perfectly with jeans, shorts, or joggers. Ideal for daily use, outings, and casual fashion with durable stitching and premium quality material.	16	9	t
45	Bag	4650.00	3	8	9	2026-05-14 15:36:27.916659+05:30	Stylish and durable men’s bag designed for everyday use, office, travel, and casual outings. Made with high-quality material and a modern design, it offers spacious compartments to carry essentials like wallet, laptop, books, and accessories comfortably. Features strong zippers, adjustable straps, and a premium finish for both comfort and style.	10	21	t
49	refg	5200.00	2	8	2	2026-05-19 09:48:32.921094+05:30	regftw4g	12	3	t
52	Ring	8500.00	3	20	8	2026-05-19 17:01:18.499902+05:30	Elegant women’s ring crafted with a stylish and modern design. Perfect for daily wear, parties, weddings, and special occasions. Lightweight, comfortable, and made with high-quality finishing for a premium look. A beautiful accessory that adds charm and elegance to every outfit.	8	17	f
53	tennis_bracelet	6000.00	3	20	8	2026-05-19 17:03:38.069792+05:30	Stylish women’s bracelet designed with an elegant and trendy look. Perfect for casual wear, parties, weddings, and special occasions. Made with premium-quality finishing, lightweight, comfortable, and easy to wear. Adds a graceful and fashionable touch to any outfit.	13	18	f
54	kids shoe	899.00	1	11	6	2026-05-19 17:35:18.737557+05:30	Comfortable and stylish kids’ shoes designed for daily wear, school, outdoor activities, and playtime. Made with soft, durable, and lightweight material to provide all-day comfort and support for growing feet. Trendy design with a secure fit, perfect for active kids.	16	12	f
\.


--
-- Data for Name: products_productimage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_productimage (id, image, product_id) FROM stdin;
135	products/ring5_uwGPDSh.jpg	52
2	products/shirt3m.jpeg	2
136	products/rings_A_wWmpjwi.jpg	52
5	products/top4w.jpg	5
139	products/bracelet_w_pErKzmL.jpg	53
140	products/shoes1k.jpeg	54
141	products/shoes_k.jpeg	54
16	products/dress5w.jpg	10
17	products/dress4w.jpg	10
18	products/dress3w.jpg	10
19	products/dress2w.jpg	10
20	products/dress1w.jpg	10
24	products/dress4k_hcWjloS.jpeg	12
25	products/ring3.jpg	13
26	products/ring5.jpg	13
27	products/bracelet4.jpeg	14
29	products/shoes1w.jpg	16
30	products/shoes2w.jpg	16
31	products/sliders2k.jpeg	17
54	products/tshirt3m_XXPJMUG.jpg	22
55	products/tshirt5m_vsFKWhH.jpeg	22
60	products/dress6k_TA6nXqV.jpg	21
61	products/jeans4w.jpg	20
62	products/jeans5w.jpg	20
63	products/jeans_w.jpg	20
66	products/bags2w.jpg	23
67	products/bags3w_ONkghDt.jpeg	23
73	products/shirt1m_XM9PCmJ.jpg	3
74	products/shirt6m.jpg	3
75	products/shirt3m_AEstCPm.jpeg	3
76	products/shirt5m.jpeg	3
80	products/necklase3.jpeg	34
81	products/necklase4.jpg	34
82	products/watches2w.jpg	33
83	products/watches4w_ty2y2iU.jpg	33
84	products/Dress1k_lZJqz8H.jpg	9
85	products/Dress_k.jpg	9
86	products/dress4k_zkrZQnU.jpeg	9
91	products/tshirt3k.jpg	36
92	products/tshirt5k.jpg	36
93	products/tshirt1k.jpeg	36
94	products/clogs1m.jpeg	37
95	products/clogs2m.jpeg	37
96	products/shorts1_7XlxgqT.jpeg	35
97	products/shorts2_BgptVPm.jpeg	35
98	products/shorts3_6twxpE0.jpeg	35
109	products/watches1w_9mNizdT.jpg	40
110	products/watches2w_Z6IRcaL.jpg	40
111	products/watches4w_X4CqNpg.jpg	40
114	products/bags1m.jpeg	42
115	products/bags2m.jpeg	42
116	products/bags1m_8owIEjG.jpeg	43
117	products/bags2m_o0jLJHW.jpeg	43
118	products/bags1m_KgyEhkC.jpeg	44
119	products/bags2m_lUzjEQw.jpeg	44
120	products/bags1m_Y6SENI7.jpeg	45
121	products/bags2m_3Ycu3sp.jpeg	45
122	products/necklase2.jpeg	46
123	products/necklase3_Jwgerqc.jpeg	46
124	products/tshirt2m_pgV2PaL.jpg	47
125	products/tshirt1m_A9gYTjL.jpeg	47
126	products/tshirt5m_xH56O9e.jpeg	47
129	products/top2w_1fot7Pp.jpg	49
130	products/top3w_YsEThQO.jpg	49
131	products/top5w_cvT8u35.jpg	49
\.


--
-- Data for Name: products_producttype; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_producttype (id, name, image, subcategory_id) FROM stdin;
1	shirt	product_types/men_shirt.jpg	1
2	jeans	product_types/men_jeans.jpg	1
3	Top	product_types/top_w.jpg	2
4	Dress	product_types/dress_w.jpg	2
5	Jeans	product_types/jeans_w.jpg	2
6	Dress	product_types/Dress_k.jpg	3
7	Shorts	product_types/shorts_k.jpg	3
8	Tshirt	product_types/tshirt_k.jpg	3
9	Tshirt	product_types/tshirt_m.jpg	1
10	shoes	product_types/shoes_w.jpg	5
11	shoes	product_types/shoes_m.jpeg	4
12	shoes	product_types/shoes_k.jpeg	6
13	Sliders	product_types/sliders_m.jpeg	4
14	Sliders	product_types/sliders_w.jpg	5
15	Sliders	product_types/sliders_k.jpeg	6
16	Clogs	product_types/clogs_m.jpg	4
17	Rings	product_types/rings_A.jpg	8
18	Bracelets	product_types/bracelet_A.jpg	8
19	Necklace	product_types/necklace_A.jpg	8
20	Women_Bags	product_types/bags4w.jpg	9
21	Men_Bags	product_types/bags2m.jpeg	9
22	Women_Watches	product_types/watches3w.jpg	7
23	Men_Watches	product_types/watches3m.jpeg	7
\.


--
-- Data for Name: products_subcategory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_subcategory (id, name, image, category_id) FROM stdin;
6	kids	subcategories/kids_footwear_68tPmWa.jpeg	1
4	men	subcategories/men_footwear_vKNbnrh.png	1
9	bags	subcategories/bags_accessories_3IY8X8u.jpg	3
7	watches	subcategories/watches_accessories.jpeg	3
8	jewellery	subcategories/jewellery_accessories_NpZoYYZ.jpeg	3
3	kids_clothes	subcategories/subcategories/kids_clothes_0xZ6J2f.png	2
2	women_clothes	subcategories/subcategories/women_clothes_mPWv1vk.jpeg	2
1	Men_clothes	subcategories/subcategories/men_clothes_uc25YNE.png	2
5	women	subcategories/women_footwear.png	1
\.


--
-- Data for Name: wishlist_wishlist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wishlist_wishlist (id, created_at, product_id, user_id) FROM stdin;
7	2026-05-08 15:50:08.598716+05:30	33	1
12	2026-05-11 14:30:48.040957+05:30	12	14
17	2026-05-12 16:35:50.397477+05:30	10	15
30	2026-05-19 17:14:23.932038+05:30	52	21
31	2026-05-20 09:21:09.95049+05:30	13	21
33	2026-05-20 10:30:40.017045+05:30	53	16
\.


--
-- Name: accounts_sellerprofile_categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_sellerprofile_categories_id_seq', 14, true);


--
-- Name: accounts_sellerprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_sellerprofile_id_seq', 10, true);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 23, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: cart_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_cart_id_seq', 5, true);


--
-- Name: cart_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_cartitem_id_seq', 67, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 107, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 37, true);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 22, true);


--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_orderitem_id_seq', 26, true);


--
-- Name: products_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_category_id_seq', 5, true);


--
-- Name: products_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_product_id_seq', 54, true);


--
-- Name: products_productimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_productimage_id_seq', 141, true);


--
-- Name: products_producttype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_producttype_id_seq', 23, true);


--
-- Name: products_subcategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_subcategory_id_seq', 9, true);


--
-- Name: wishlist_wishlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wishlist_wishlist_id_seq', 33, true);


--
-- Name: accounts_sellerprofile_categories accounts_sellerprofile_c_sellerprofile_id_categor_849339b7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_sellerprofile_categories
    ADD CONSTRAINT accounts_sellerprofile_c_sellerprofile_id_categor_849339b7_uniq UNIQUE (sellerprofile_id, category_id);


--
-- Name: accounts_sellerprofile_categories accounts_sellerprofile_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_sellerprofile_categories
    ADD CONSTRAINT accounts_sellerprofile_categories_pkey PRIMARY KEY (id);


--
-- Name: accounts_sellerprofile accounts_sellerprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_sellerprofile
    ADD CONSTRAINT accounts_sellerprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_sellerprofile accounts_sellerprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_sellerprofile
    ADD CONSTRAINT accounts_sellerprofile_user_id_key UNIQUE (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: cart_cart cart_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_pkey PRIMARY KEY (id);


--
-- Name: cart_cartitem cart_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_orderitem orders_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_pkey PRIMARY KEY (id);


--
-- Name: products_category products_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: products_productimage products_productimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_productimage
    ADD CONSTRAINT products_productimage_pkey PRIMARY KEY (id);


--
-- Name: products_producttype products_producttype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_producttype
    ADD CONSTRAINT products_producttype_pkey PRIMARY KEY (id);


--
-- Name: products_subcategory products_subcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_subcategory
    ADD CONSTRAINT products_subcategory_pkey PRIMARY KEY (id);


--
-- Name: wishlist_wishlist wishlist_wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_pkey PRIMARY KEY (id);


--
-- Name: accounts_sellerprofile_categories_category_id_7816cbce; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_sellerprofile_categories_category_id_7816cbce ON public.accounts_sellerprofile_categories USING btree (category_id);


--
-- Name: accounts_sellerprofile_categories_sellerprofile_id_45a15030; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_sellerprofile_categories_sellerprofile_id_45a15030 ON public.accounts_sellerprofile_categories USING btree (sellerprofile_id);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: cart_cart_user_id_9b4220b9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_cart_user_id_9b4220b9 ON public.cart_cart USING btree (user_id);


--
-- Name: cart_cartitem_cart_id_370ad265; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_cartitem_cart_id_370ad265 ON public.cart_cartitem USING btree (cart_id);


--
-- Name: cart_cartitem_product_id_b24e265a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_cartitem_product_id_b24e265a ON public.cart_cartitem USING btree (product_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: orders_order_buyer_id_26195532; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_buyer_id_26195532 ON public.orders_order USING btree (buyer_id);


--
-- Name: orders_orderitem_order_id_fe61a34d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_order_id_fe61a34d ON public.orders_orderitem USING btree (order_id);


--
-- Name: orders_orderitem_product_id_afe4254a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_product_id_afe4254a ON public.orders_orderitem USING btree (product_id);


--
-- Name: orders_orderitem_seller_id_73da5f24; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_seller_id_73da5f24 ON public.orders_orderitem USING btree (seller_id);


--
-- Name: products_product_category_id_9b594869; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_product_category_id_9b594869 ON public.products_product USING btree (category_id);


--
-- Name: products_product_product_type_id_bf0c089a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_product_product_type_id_bf0c089a ON public.products_product USING btree (product_type_id);


--
-- Name: products_product_seller_id_07afb1e3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_product_seller_id_07afb1e3 ON public.products_product USING btree (seller_id);


--
-- Name: products_product_subcategory_id_b28a1e3b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_product_subcategory_id_b28a1e3b ON public.products_product USING btree (subcategory_id);


--
-- Name: products_productimage_product_id_e747596a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_productimage_product_id_e747596a ON public.products_productimage USING btree (product_id);


--
-- Name: products_producttype_subcategory_id_cbd1cc20; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_producttype_subcategory_id_cbd1cc20 ON public.products_producttype USING btree (subcategory_id);


--
-- Name: products_subcategory_category_id_44d297b7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_subcategory_category_id_44d297b7 ON public.products_subcategory USING btree (category_id);


--
-- Name: wishlist_wishlist_product_id_2d08b75d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_wishlist_product_id_2d08b75d ON public.wishlist_wishlist USING btree (product_id);


--
-- Name: wishlist_wishlist_user_id_13f28b16; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_wishlist_user_id_13f28b16 ON public.wishlist_wishlist USING btree (user_id);


--
-- Name: accounts_sellerprofile_categories accounts_sellerprofi_category_id_7816cbce_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_sellerprofile_categories
    ADD CONSTRAINT accounts_sellerprofi_category_id_7816cbce_fk_products_ FOREIGN KEY (category_id) REFERENCES public.products_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_sellerprofile_categories accounts_sellerprofi_sellerprofile_id_45a15030_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_sellerprofile_categories
    ADD CONSTRAINT accounts_sellerprofi_sellerprofile_id_45a15030_fk_accounts_ FOREIGN KEY (sellerprofile_id) REFERENCES public.accounts_sellerprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_sellerprofile accounts_sellerprofile_user_id_8976d036_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_sellerprofile
    ADD CONSTRAINT accounts_sellerprofile_user_id_8976d036_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cart cart_cart_user_id_9b4220b9_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_user_id_9b4220b9_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cartitem cart_cartitem_cart_id_370ad265_fk_cart_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_cart_id_370ad265_fk_cart_cart_id FOREIGN KEY (cart_id) REFERENCES public.cart_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cartitem cart_cartitem_product_id_b24e265a_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_product_id_b24e265a_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_buyer_id_26195532_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_buyer_id_26195532_fk_accounts_user_id FOREIGN KEY (buyer_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_order_id_fe61a34d_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_order_id_fe61a34d_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_product_id_afe4254a_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_product_id_afe4254a_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_seller_id_73da5f24_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_seller_id_73da5f24_fk_accounts_user_id FOREIGN KEY (seller_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_category_id_9b594869_fk_products_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_category_id_9b594869_fk_products_category_id FOREIGN KEY (category_id) REFERENCES public.products_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_product_type_id_bf0c089a_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_product_type_id_bf0c089a_fk_products_ FOREIGN KEY (product_type_id) REFERENCES public.products_producttype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_seller_id_07afb1e3_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_seller_id_07afb1e3_fk_accounts_user_id FOREIGN KEY (seller_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_subcategory_id_b28a1e3b_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_subcategory_id_b28a1e3b_fk_products_ FOREIGN KEY (subcategory_id) REFERENCES public.products_subcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productimage products_productimag_product_id_e747596a_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_productimage
    ADD CONSTRAINT products_productimag_product_id_e747596a_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_producttype products_producttype_subcategory_id_cbd1cc20_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_producttype
    ADD CONSTRAINT products_producttype_subcategory_id_cbd1cc20_fk_products_ FOREIGN KEY (subcategory_id) REFERENCES public.products_subcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_subcategory products_subcategory_category_id_44d297b7_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_subcategory
    ADD CONSTRAINT products_subcategory_category_id_44d297b7_fk_products_ FOREIGN KEY (category_id) REFERENCES public.products_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlist_wishlist wishlist_wishlist_product_id_2d08b75d_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_product_id_2d08b75d_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlist_wishlist wishlist_wishlist_user_id_13f28b16_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_user_id_13f28b16_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict GaERDaLYLIsX3TlRd2HOfnXNFaaGQSDWzx4CyaA83SYKoWbJ1ItgOpfWjLJrifh

