services:

  web:
    build: .

    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application

    volumes:
      - .:/app

    ports:
      - "8001:8000"

    depends_on:
      - db

    env_file:
      - .env
  db:
    image: postgres:18

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - docker_mvtdemo_db:/var/lib/postgresql

  redis:
    image: redis
    container_name: redis_broker
    ports:
      - "6380:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A config worker -l info
    depends_on:
      - redis
    volumes:
      - .:/app

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A config beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery_worker

volumes:
  docker_mvtdemo_db: