# Generated by Django 6.0.4 on 2026-05-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Packed', 'packed'), ('Shipped', 'shipped'), ('Delivered', 'delivered'), ('Cancelled', 'cancelled')], default='Pending', max_length=20),
        ),
    ]
