# Generated by Django 6.0.4 on 2026-05-19 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_orderitem_status"),
        ("products", "0008_product_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitem",
                to="products.product",
            ),
        ),
    ]
