# Generated by Django 6.0.4 on 2026-05-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
