# Generated by Django 6.0.4 on 2026-05-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_delete_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
